name: 'Test coverage check'
description: 'Check coverage and annotate uncovered code in PR'
author: 'inzephirum'
inputs:
  github_token:
    required: true
    description: 'Github token'
  report_file_path:
    required: true
    description: 'Path to lcov file'
  min_threshold:
    description: 'Min percentage of coverage'
    default: '100'

runs:
  using: 'node12'
  main: 'dist/index.js'
