name: 'build-test'
on:
  pull_request:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  pr-coverage: # create pr coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run coverage

      - name: Save code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info


  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: pr-coverage
    steps:
      - uses: actions/checkout@v2
      - name: Download code coverage report
        uses: actions/download-artifact@v2
        with:
          name: ref-lcov.info
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_threshold: '100'
          report_file_path: './lcov.info'
